<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114021024 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE amst (vondstnummer VARCHAR(32) DEFAULT NULL, project_code VARCHAR(24) DEFAULT NULL, categorie VARCHAR(3) DEFAULT NULL, fragmenten INT DEFAULT NULL, begin_dat INT DEFAULT NULL, eind_dat INT DEFAULT NULL, put INT DEFAULT NULL, vlak VARCHAR(2) DEFAULT NULL, spoor INT DEFAULT NULL, website INT DEFAULT NULL, munt_land_geografisch VARCHAR(32) DEFAULT NULL, munt_autoriteit_politiek VARCHAR(48) DEFAULT NULL, munt_muntsoort VARCHAR(48) DEFAULT NULL, munt_eenheid_waarde INT DEFAULT NULL, munt_muntplaats_productieplaats VARCHAR(32) DEFAULT NULL, munt_lengte_diameter_in_mm INT DEFAULT NULL, citation_url VARCHAR(160) DEFAULT NULL, code VARCHAR(22) NOT NULL, trefwoorden VARCHAR(26) DEFAULT NULL, metaal_grootstehoogte_mm INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, vlak_min VARCHAR(255) DEFAULT NULL, vlak_max DOUBLE PRECISION DEFAULT NULL, object_backing VARCHAR(255) DEFAULT NULL, description_backing TEXT DEFAULT NULL, subcategorie_backing VARCHAR(128) DEFAULT NULL, niveau1_backing VARCHAR(255) DEFAULT NULL, niveau2_backing VARCHAR(255) DEFAULT NULL, niveau3_backing VARCHAR(255) DEFAULT NULL, niveau4_backing VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE media (id VARCHAR(32) NOT NULL, status VARCHAR(255) NOT NULL, provider VARCHAR(100) DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, external_url TEXT DEFAULT NULL, raw_data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, thumbnail_url TEXT DEFAULT NULL, location JSON DEFAULT NULL, tags JSON NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, duration INT DEFAULT NULL, file_size BIGINT DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, title TEXT DEFAULT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, camera VARCHAR(255) DEFAULT NULL, exif_data JSON DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, view_count INT DEFAULT NULL, like_count INT DEFAULT NULL, chapters JSON DEFAULT NULL, subtitles JSON DEFAULT NULL, artist VARCHAR(255) DEFAULT NULL, album VARCHAR(255) DEFAULT NULL, bitrate INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('DROP TABLE amst');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
