<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251215155305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE amst (vondstnummer VARCHAR(16) DEFAULT NULL, project_code VARCHAR(4) DEFAULT NULL, categorie VARCHAR(3) DEFAULT NULL, fragmenten INT DEFAULT NULL, begin_dat INT DEFAULT NULL, eind_dat INT DEFAULT NULL, put INT DEFAULT NULL, vlak VARCHAR(2) DEFAULT NULL, spoor INT DEFAULT NULL, website INT DEFAULT NULL, munt_land_geografisch VARCHAR(11) DEFAULT NULL, munt_autoriteit_politiek VARCHAR(8) DEFAULT NULL, munt_muntsoort VARCHAR(7) DEFAULT NULL, munt_eenheid_waarde INT DEFAULT NULL, munt_muntplaats_productieplaats VARCHAR(8) DEFAULT NULL, munt_lengte_diameter_in_mm INT DEFAULT NULL, citation_url VARCHAR(60) DEFAULT NULL, code VARCHAR(16) NOT NULL, trefwoorden VARCHAR(26) DEFAULT NULL, metaal_grootstehoogte_mm INT DEFAULT NULL, image VARCHAR(77) DEFAULT NULL, vlak_min VARCHAR(255) DEFAULT NULL, vlak_max DOUBLE PRECISION DEFAULT NULL, object_backing VARCHAR(255) DEFAULT NULL, description_backing TEXT DEFAULT NULL, subcategorie_backing VARCHAR(19) DEFAULT NULL, niveau1_backing VARCHAR(255) DEFAULT NULL, niveau2_backing VARCHAR(255) DEFAULT NULL, niveau3_backing VARCHAR(255) DEFAULT NULL, niveau4_backing VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE str (hash VARCHAR(64) NOT NULL, original TEXT NOT NULL, src_locale VARCHAR(8) NOT NULL, context VARCHAR(128) DEFAULT NULL, meta JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT NULL, locale_statuses JSONB DEFAULT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE TABLE str_translation (meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT NULL, hash VARCHAR(40) NOT NULL, str_hash VARCHAR(32) NOT NULL, locale VARCHAR(8) NOT NULL, text TEXT DEFAULT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE INDEX str_tr_str_hash_idx ON str_translation (str_hash)');
        $this->addSql('CREATE INDEX str_tr_locale_idx ON str_translation (locale)');
        $this->addSql('CREATE INDEX str_tr_str_hash_locale_idx ON str_translation (str_hash, locale)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE amst');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_translation');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
